-- Insert sample species data
INSERT INTO species (scientific_name, common_name, family, genus, species_code, conservation_status, description, habitat) VALUES
('Panthera leo', 'African Lion', 'Felidae', 'Panthera', 'PLEO', 'VU', 'Large cat native to Africa and India', 'Savannas, grasslands, and open woodlands'),
('Loxodonta africana', 'African Elephant', 'Elephantidae', 'Loxodonta', 'LAFR', 'EN', 'Largest living terrestrial animal', 'Savannas, forests, deserts, and marshes'),
('Acinonyx jubatus', 'Cheetah', 'Felidae', 'Acinonyx', 'AJUB', 'VU', 'Fastest land animal', 'Open grasslands and savannas'),
('Giraffa camelopardalis', 'Giraffe', 'Giraffidae', 'Giraffa', 'GCAM', 'VU', 'Tallest mammal', 'Savannas, grasslands, and open woodlands'),
('Hippopotamus amphibius', 'Hippopotamus', 'Hippopotamidae', 'Hippopotamus', 'HAMP', 'VU', 'Large, semi-aquatic mammal', 'Rivers, lakes, and wetlands'),
('Equus quagga', 'Plains Zebra', 'Equidae', 'Equus', 'EQUA', 'NT', 'Wild horse with black and white stripes', 'Grasslands and savannas'),
('Connochaetes taurinus', 'Blue Wildebeest', 'Bovidae', 'Connochaetes', 'CTAU', 'LC', 'Large antelope', 'Grasslands and savannas'),
('Taurotragus oryx', 'Common Eland', 'Bovidae', 'Taurotragus', 'TORY', 'LC', 'Largest antelope', 'Savannas and grasslands'),
('Phacochoerus africanus', 'Common Warthog', 'Suidae', 'Phacochoerus', 'PAFR', 'LC', 'Wild pig species', 'Savannas, woodlands, and grasslands'),
('Struthio camelus', 'Common Ostrich', 'Struthionidae', 'Struthio', 'SCAM', 'LC', 'Largest living bird', 'Savannas and open grasslands');

-- Insert sample users (passwords will be set properly by the application)
INSERT INTO users (username, email, first_name, last_name, role, password_hash) VALUES
('admin', 'admin@example.com', 'Admin', 'User', 'admin', 'placeholder_hash'),
('researcher1', 'researcher@example.com', 'Jane', 'Smith', 'researcher', 'placeholder_hash'),
('observer1', 'observer@example.com', 'John', 'Doe', 'observer', 'placeholder_hash');

-- The actual password hashes will be generated by the application
-- Default passwords: admin123, researcher123, observer123